# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:20
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obec', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='longitude/latitude')),
            ],
        ),
    ]
