# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0002_mesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesto',
            name='kod_kraje',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mesto',
            name='kod_obce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesto',
            name='kod_okresu',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='mesto',
            name='kraj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mesto',
            name='okres',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mesto',
            name='psc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
