# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cr', '0006_okresy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesto',
            name='krajske_mesto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesto',
            name='okresni_mesto',
            field=models.BooleanField(default=False),
        ),
    ]
